language: ruby
sudo: false
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
gemfile:
  - gemfiles/as4.gemfile
  - gemfiles/as5.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - xvfb-run bundle exec rake
